FROM nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV USERNAME=ros
ENV ROS_PYTHON_VERSION=3
ENV ROS_DISTRO=noetic
ENV ROBOT_IP=192.168.1.3
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

SHELL ["/bin/bash", "-c"]

# Install ROS and essential packages
RUN apt-get update \
    && apt-get install -y \
    ros-noetic-desktop-full \
    nano \
    curl \
    git \
    wget \
    gdb \
    iputils-ping \
    python3-pip \
    python3-catkin-tools \
    python3-rosdep

# Setup ROS repositories
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release \
    && curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - \
    && echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list

# Setup miniconda nad avoid pythonpath conflict when not using miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && chmod +x Miniconda3-latest-Linux-x86_64.sh \
    && ./Miniconda3-latest-Linux-x86_64.sh -b -u -p /home/$USERNAME/miniconda3 \
    && rm Miniconda3-latest-Linux-x86_64.sh \
    # && echo 'export PATH=/home/$USERNAME/miniconda3/bin${PATH:+:${PATH}}' >> /home/$USERNAME/.bashrc \
    # && echo '
    # # Only set PYTHONPATH if not using Miniconda
    # if [[ "$PATH" != *"miniconda3"* ]]; then
    #     export PYTHONPATH=/opt/ros/noetic/lib/python3/dist-packages
    # fi' >> /home/$USERNAME/.bashrc \
    && source /home/$USERNAME/miniconda3/bin/activate \
    && conda init bash

# Configure conda environment
RUN conda create -n python3.9-env python=3.9 -y \
    && conda activate python3.9-env

# Install necessary ROS python 
RUN pip3 install rospkg empy==3.3.2

# Create the "ros" user with the host user's IDs
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN adduser --disabled-password --gecos '' $USERNAME \
    && usermod  --uid $USER_ID $USERNAME \
    && groupmod --gid $GROUP_ID $USERNAME \
    && usermod --shell /bin/bash $USERNAME \
    && adduser $USERNAME sudo \
    && adduser $USERNAME dialout \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER $USERNAME

# # Setup CUDA environment
# RUN echo 'export PATH=/usr/local/cuda-11.3/bin${PATH:+:${PATH}}' >> /home/$USERNAME/.bashrc \
#     && echo 'export LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}' >> /home/$USERNAME/.bashrc \
#     && echo 'export ROBOT_IP=$ROBOT_IP' >> /home/$USERNAME/.bashrc \
#     && echo 'export ROS_HOSTNAME=localhost' >> /home/$USERNAME/.bashrc \
#     && echo 'export ROS_MASTER_URI=http://localhost:11311' >> /home/$USERNAME/.bashrc 

# Rest of your existing Dockerfile remains the same, starting from:
RUN mkdir -p /home/$USERNAME/catkin_ws/src \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME/catkin_ws
WORKDIR /home/$USERNAME/catkin_ws

# Copy code into workspace
COPY --chown=$USERNAME ./noetic_src src

RUN sudo mkdir -p /etc/apt/keyrings \
    && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null \
    && sudo apt-get install -y apt-transport-https \
    && echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/librealsense.list \
    && sudo apt-get update \
    && sudo apt-get install -y \
        usbutils \
        librealsense2-dkms \
        librealsense2-utils \
        librealsense2-dev \
        librealsense2-dbg \
    && sudo apt-get upgrade -y \
    && sudo rm -rf /var/lib/apt/lists/*

# Configure User access to realsense devices
RUN sudo usermod -a -G plugdev $USERNAME

# Install PyTorch suitable for CUDA 11.3
# RUN pip3 install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 \
#     --extra-index-url https://download.pytorch.org/whl/cu113 
RUN pip3 install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 \
    --extra-index-url https://download.pytorch.org/whl/cu113 

# Install OVGNet dependency
RUN cd /home/$USERNAME/catkin_ws/src/OVGNet/ \
    && export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True \
    && pip3 install -r requirements.txt

# Install necessary GroundingDino dependency
RUN cd /home/$USERNAME/catkin_ws/src/OVGNet/groundingdino \
    && pip3 install -e .

RUN cd /home/$USERNAME/catkin_ws/src/groundingdino-ros/src/groundingdino \
    && pip3 install -e .

# Install necessary graspnet model dependency
RUN cd /home/$USERNAME/catkin_ws/src/OVGNet/graspnet/graspnet/pointnet2 \
    && python3 setup.py install \
    && cd /home/$USERNAME/catkin_ws/src/OVGNet/graspnet/graspnet/knn \
    && python3 setup.py install

RUN cd /home/$USERNAME/catkin_ws/src/graspnet-ros/src/pointnet2 \
    && python3 setup.py install \
    && cd /home/$USERNAME/catkin_ws/src/graspnet-ros/src/knn \
    && python3 setup.py install

# Install Open-GroundingDino for test Visual Grounding implementation
RUN cd /home/$USERNAME/catkin_ws/src/OVGNet/test_vg/Open-GroundingDino \
    && pip3 install -r requirements.txt \
    && cd /home/$USERNAME/catkin_ws/src/OVGNet/test_vg/Open-GroundingDino/models/GroundingDINO/ops \
    && python3 setup.py build install \
    && python3 test.py

# Source ROS environment
RUN conda activate python3.9-env \
    && cd /home/$USERNAME/catkin_ws \
    && catkin init \
    && rosdep init && rosdep update \
    && sudo apt-get update \
    && rosdep install --from-paths . --ignore-src -r -y --rosdistro=$ROS_DISTRO \
    && catkin build

# Roundabout ffi_pointer_error, version libffi_base_7.0
RUN echo 'export LD_LIBRARY_PATH=/home/$USERNAME/miniconda3/envs/python3.9-env/lib:$LD_LIBRARY_PATH' >> /home/$USERNAME/.bashrc \
    && ln -sf /usr/lib/x86_64-linux-gnu/libffi.so.7 /home/ros/miniconda3/envs/python3.9-env/lib/libffi.so.7

RUN sudo apt-get update \
    && sudo apt-get upgrade -y \
    && echo 'source /opt/$USERNAME/$ROS_DISTRO/setup.bash' >> /home/$USERNAME/.bashrc \
    && echo 'source /home/$USERNAME/catkin_ws/devel/setup.bash' >> /home/$USERNAME/.bashrc \
    && echo 'source /home/$USERNAME/miniconda3/bin/activate' >> /home/$USERNAME/.bashrc
